fixed paint scale component - now javafx only
Caused by: java.lang.NoClassDefFoundError: jdk/swing/interop/LightweightContentWrapper
	at javafx.embed.swing.SwingNode.<init>(SwingNode.java:263)
	at io.github.mzmine.parameters.parametertypes.PaintScaleComponent.<init>(PaintScaleComponent.java:53)